version: '3'
services:
  leader:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go-repl
    ports:
      - 8080:5000
    env_file: docker.env
    environment:
      ROLE: leader
  follower_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go-repl
    ports:
      - 8081:5000
    env_file: docker.env
    environment:
      ROLE: follower
  follower_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: go-repl
    ports:
      - 8082:5000
    env_file: docker.env
    environment:
      ROLE: follower
